### PR TITLE
Add permissions to example yml files

### PR DESCRIPTION
**Pull request by TurnrDev**
This action requires the checks: write permission so I've added an example in the readme to save people from digging around to find the right permission

### CODE REVIEW

**Comment by j-catania** [comment]
Hi @TurnrDev,

What was your error ?
I never had this permissions for using this Action

**Comment by TurnrDev** [comment]
Insufficient permissions. On your repo you use the action on, do you have the workflow permissions set to all scopes, or read only?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions

If you have it set to read only (a sensible thing to do when adding third party actions), you'll need to manually define which permissions get write access in a workflow.

**Comment by j-catania** [comment]
You are right, I remember when I changed this settings.
Thanks for your contribution 🙏🏽

**Comment by TurnrDev** [comment]
No worries, happy to help

**Pull request merged**
