### PR TITLE
Update checkout and upload-artifact actions versions

### PR DESCRIPTION
**Pull request by Akaame**

### CODE REVIEW

**Comment by jozefizso** [comment]
It is not apparent from the build checks, but these changes are failing the workflow: https://github.com/dorny/test-reporter/actions/runs/8596798196

**Comment by Akaame** [comment]
@jozefizso interesting, I do not think it is related to my changeset actually. Am I the first outside contributor who had auth problems for the download artifact action in this pipeline?

**Comment by Akaame** [comment]
https://github.com/dorny/test-reporter/pull/420 created this and just realized the CI action ignores the `*.md`.

**Comment by abelbraaksma** [comment]
Related: https://github.com/dorny/test-reporter/issues/343

**Review by jozefizso — APPROVED** [review]

**Pull request merged**
