### PR TITLE
Add dependabot configuration

### PR DESCRIPTION
**Pull request by yeikel**
See https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

See https://github.com/dorny/test-reporter/issues/227 as well

### CODE REVIEW

**Review by gaby — CHANGES_REQUESTED** [review]
Can you also add github-actions ?

```
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: daily
```

**Comment by yeikel** [comment]
> Can you also add github-actions ?
> 
> ```
>   - package-ecosystem: "github-actions"
>     directory: "/"
>     schedule: 
>       interval: daily
> ```

Thank you. Pushed it with 279d40aa15a47c835a7ddd7f51c6b8e3c49ae79d

**Review by gaby — APPROVED** [review]
LGTM

**Comment by gaby** [comment]
@dorny This PR would help ease maintenance of dependencies.

**Pull request merged**
