### PR TITLE
Merge `v1` branch to `main`

### PR DESCRIPTION
**Pull request by jozefizso**

### CODE REVIEW

**Comment by jcorreia-forbesadvisor** [comment]
@jozefizso this broke all actions currently pointing to `uses: dorny/test-reporter@v1` as branch no longer exists.

Is there another recommended way to access a major version or shouldn't we be doing it at all?

**Comment by TheSench** [comment]
The pattern of using `v1` for the latest `v1.x` is common, and is even used by all of the [official actions provided by GitHub](https://github.com/actions).

**Comment by jozefizso** [comment]
Thanks for point this out, @TheSench. The `v1` branch should not been deleted.

**Comment by TheSench** [comment]
In other actions, I typically see this managed as a tag instead of a branch.  I'm guessing the `v1` branch was not marked as a protected branch and was deleted upon merging to `main`?

**Comment by TheSench** [comment]
Thanks for the quick restoration.

**Comment by jozefizso** [comment]
It's a branch so people can make PRs against it, eg. #517

Yes, it does not have branch protection rules, as I don't have access to repository settings.

**Pull request merged**
